ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.spotik.server.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/spotik"
    url = ${?DATABASE_URL}
    user = "spotik"
    user = ${?DATABASE_USER}
    password = "spotik_secret"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
}

jwt {
    secret = "spotik-jwt-secret-change-in-production-2024"
    secret = ${?JWT_SECRET}
    issuer = "spotik-server"
    audience = "spotik-app"
    realm = "Spotik"
    expiresInMs = 604800000  # 7 days
}

